server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_order
    username: postgres
    password: your_secure_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orders
  flyway:
    enabled: true
    default-schema: orders
    schemas: orders,inventory,public
    create-schemas: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_secure_pass}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}


vnp:
  tmn-code: ${VNP_TMN_CODE:2QX7C6YK}
  hash-secret: ${VNP_HASH_SECRET:HJDFYUREIYOWQDNBVCHFYTRUEIORPWQA}
  url: ${VNP_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNP_RETURN_URL:http://localhost:8080/api/v1/payments/vnpay-return}

app:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8082}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
